Skills{
'Acrobatics': 0,
'Bluff': 0,
'Climb': 0,
'Diplomacy': 0,
'Disable Device': 0,
'Disguise': 0,
'Escape Artist': 0,
'Fly': 0,
'Heal': 0,
'Intimidate': 0,
'Knowledge (arcana)': 0,
'Knowledge (dungeoneering)': 0,
'Knowledge (local)': 0,
'Knowledge (nature)': 0,
'Knowledge (planes)': 0,
'Knowledge (religion)': 0,
'Perception': 0,
'Ride': 0,
'Sense Motive': 0,
'Spellcraft': 0,
'Stealth': 0,
'Survival': 0,
'Swim': 0,
'Use Magic Device': 0,
'Appraise': 0,
'Craft': 0,
'Handle Animal': 0,
'Knowledge (engineering)': 0,
'Knowledge (geography)': 0,
'Knowledge (history)': 0,
'Knowledge (nobility)': 0,
'Linguistics': 0,
'Perform': 0,
'Profession': 0,
'Sleight of Hand': 0}

Warrior_1{'Handle Animal': 5,'Perception': 5}
Adept_1{'Spellcraft': 5,'Survival': 9,'Knowledge_religion': 5,'Heal': 9}
Expert_1{'Craft_brewery': 8,'Craft_carpender': 8,'Handle Animal': 4,'Perception': 5,'Survival': 5,'Knowledge (geography)': 8,'Knowledge (history)': 6,'Knowledge (local)': 5}
Commoner_1{'Handle Animal': 8,'Profession_farmer': 8,'Perception': 6}